"""Initial migration.

Revision ID: 80196e113fec
Revises: 
Create Date: 2024-06-15 20:18:48.069785

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80196e113fec'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_deleted', sa.Boolean(), nullable=True))

    with op.batch_alter_table('cart_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_deleted', sa.Boolean(), nullable=True))

    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_deleted', sa.Boolean(), nullable=True))

    with op.batch_alter_table('order_details', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_deleted', sa.Boolean(), nullable=True))

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_deleted', sa.Boolean(), nullable=True))

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_deleted', sa.Boolean(), nullable=True))

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_deleted', sa.Boolean(), nullable=True))

    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_deleted', sa.Boolean(), nullable=True))

    with op.batch_alter_table('shipping_addresses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_deleted', sa.Boolean(), nullable=True))

    with op.batch_alter_table('suppliers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_deleted', sa.Boolean(), nullable=True))

    with op.batch_alter_table('warehouse', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_deleted', sa.Boolean(), nullable=True))

    with op.batch_alter_table('warehouse_stock', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_deleted', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('warehouse_stock', schema=None) as batch_op:
        batch_op.drop_column('is_deleted')

    with op.batch_alter_table('warehouse', schema=None) as batch_op:
        batch_op.drop_column('is_deleted')

    with op.batch_alter_table('suppliers', schema=None) as batch_op:
        batch_op.drop_column('is_deleted')

    with op.batch_alter_table('shipping_addresses', schema=None) as batch_op:
        batch_op.drop_column('is_deleted')

    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.drop_column('is_deleted')

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('is_deleted')

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_column('is_deleted')

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('is_deleted')

    with op.batch_alter_table('order_details', schema=None) as batch_op:
        batch_op.drop_column('is_deleted')

    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_column('is_deleted')

    with op.batch_alter_table('cart_items', schema=None) as batch_op:
        batch_op.drop_column('is_deleted')

    with op.batch_alter_table('cart', schema=None) as batch_op:
        batch_op.drop_column('is_deleted')

    # ### end Alembic commands ###
